# The Jisho API url to use for lookups
# Default value: https://jisho.org/api/v1
api_base_url: https://jisho.org/api/v1

# How many dictionary definitions to return, at most. Use zero for no limit.
# Value has to be zero or a positive integer.
# Default value: 3
max_results_default: 3

# For possible values, see: https://pypi.org/project/termcolor/
warning_text_color: yellow # Default value: yellow
success_text_color: green # Default value: green

# By default, the script makes sure its name matches
# this config file's path, for naming consistency.
# You can ignore this check by changing this value to True.
# Default value: False
ignore_script_name_mismatch: False
